In [ ]:
import pandas as pd
df_cst=pd.read_csv('/content/AWCustomers.csv')
print(df_cst.shape)
head=[df_cst['Occupation'],df_cst['Gender'],df_cst['HomeOwnerFlag'],df_cst['NumberCarsOwned'],df_cst['NumberChildrenAtHome'],df_cst['TotalChildren'],df_cst['YearlyIncome']]
df=pd.concat(head,axis=1)
df.head()
#Occupation-Discrete(Ordinal)
#Gender-Discrete(Nominal)
#HomeOwnerFlag-Discrete(Nominal)
#NumberCarsOwned-Discrete(Nominal)
#totalChildren-Discrete(Nominal)
#YearlyIncome-Continous


(18361, 24)


Occupation Gender  ...  TotalChildren  YearlyIncome
0        Clerical      M  ...              1         81916
1        Clerical      M  ...              2         81076
2        Clerical      F  ...              0         86387
3  Skilled Manual      M  ...              2         61481
4  Skilled Manual      M  ...              0         51804

[5 rows x 7 columns]

In [ ]:
df.isnull().sum()
df=df.dropna()

In [ ]:
import numpy as np

In [ ]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns[2:]:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result
df1=normalize(df)
df1.head()

Occupation Gender  ...  TotalChildren  YearlyIncome
0        Clerical      M  ...       0.333333      0.496842
1        Clerical      M  ...       0.666667      0.489453
2        Clerical      F  ...       0.000000      0.536172
3  Skilled Manual      M  ...       0.666667      0.317083
4  Skilled Manual      M  ...       0.000000      0.231958

[5 rows x 7 columns]

In [ ]:
df1['YearlyIncome'] = pd.cut(df1['YearlyIncome'], bins=10,labels=[i for i in range(1,11)])
df1.head()

Occupation Gender  ...  TotalChildren  YearlyIncome
0        Clerical      M  ...       0.333333             5
1        Clerical      M  ...       0.666667             5
2        Clerical      F  ...       0.000000             6
3  Skilled Manual      M  ...       0.666667             4
4  Skilled Manual      M  ...       0.000000             3

[5 rows x 7 columns]

In [ ]:
def standard(df):
    result = df.copy()
    for feature_name in df.columns[2:]:
        sd_value = df[feature_name].std()
        mean_value = df[feature_name].mean()
        result[feature_name] = (df[feature_name] - mean_value) / (sd_value)
    return result
df1=standard(df)
df1.head()

Occupation Gender  ...  TotalChildren  YearlyIncome
0        Clerical      M  ...       0.161337      0.298547
1        Clerical      M  ...       1.239719      0.271173
2        Clerical      F  ...      -0.917044      0.444249
3  Skilled Manual      M  ...       1.239719     -0.367391
4  Skilled Manual      M  ...      -0.917044     -0.682747

[5 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
data=enc.fit_transform(df1.Gender.values.reshape(-1,1)).toarray().astype(int)
print(data)
df2=pd.DataFrame(data, columns =['Female', 'Male'])
df1 = pd.concat([df1,df2], axis=1)
data=enc.fit_transform(df1.Occupation.values.reshape(-1,1)).toarray().astype(int)
print(data)
df2=pd.DataFrame(data, columns =['Occupation_Clerical',	'Occupation_Management',	'Occupation_Manual',	'Occupation_Professional',	'Occupation_Skilled Manual'])
df1 = pd.concat([df1,df2], axis=1)
df1=df1.drop(['Occupation','Gender'],axis=1)
df1.head()

[[0 1]
 [0 1]
 [1 0]
 ...
 [1 0]
 [1 0]
 [1 0]]
[[1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 ...
 [0 0 0 0 1]
 [1 0 0 0 0]
 [0 0 0 1 0]]


HomeOwnerFlag  ...  Occupation_Skilled Manual
0       0.798581  ...                          0
1       0.798581  ...                          0
2      -1.252153  ...                          0
3       0.798581  ...                          1
4       0.798581  ...                          1

[5 rows x 12 columns]

In [ ]:
from math import*
 
def square_rooted(x):
  return round(sqrt(sum([a*a for a in x])),3)
 
def cosine_similarity(x,y):
  numerator = sum(a*b for a,b in zip(x,y))
  denominator = square_rooted(x)*square_rooted(y)
  return round(numerator/float(denominator),3)
 
print(cosine_similarity(df1['Occupation_Management'],df1['Occupation_Clerical']))

0.0


In [ ]:
def similar(x,y):
  sum11,sum00,sum01,sum10=0,0,0,0
  for i in range(len(x)):
    if x[i]==1 and y[i]==1:
      sum11+=1
    elif x[i]==0 and y[i]==0:
      sum00+=1
    elif x[i]==0 and y[i]==1:
      sum01+=1
    else:
      sum10+=1
  similar_coff=(sum11+sum00)/(len(x))
  jaccard_coff=sum11/(len(x)-sum00)
  return(similar_coff,jaccard_coff)
x,y=similar(df1['Occupation_Management'],df1['Occupation_Clerical'])
print('similar_coeff=',x)
print('jaccard_coeff=',y)

similar_coeff= 0.6012199771254289
jaccard_coeff= 0.0


In [ ]:
from numpy import cov
covariance = cov(df1['YearlyIncome'], df1['NumberCarsOwned'])
print(covariance)

[[1.         0.47730015]
 [0.47730015 1.        ]]
