#### Name : Soumya Swaraj
#### Roll : 101803573

#### Batch : COE26

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/home/USA_Housing.csv')
df.head()

Avg. Area Income  Avg. Area House Age  ...  Area Population         Price
0       79545.45857             5.682861  ...      23086.80050  1.059034e+06
1       79248.64245             6.002900  ...      40173.07217  1.505891e+06
2       61287.06718             5.865890  ...      36882.15940  1.058988e+06
3       63345.24005             7.188236  ...      34310.24283  1.260617e+06
4       59982.19723             5.040555  ...      26354.10947  6.309435e+05

[5 rows x 6 columns]

In [4]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

**Q1**


In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_scale = sc.fit_transform(x)
x_scale = np.insert(x_scale,0,values=1,axis=1)

In [16]:
from sklearn.model_selection import RepeatedKFold
from sklearn.metrics import r2_score 
kf = RepeatedKFold(n_splits = 5, n_repeats = 1, random_state = None) 
betas = []
errors = []
r2 = []
for train_index,test_index in kf.split(x_scale):
  print("Train:", train_index, "Validation:",test_index)
  x_train,x_test = x_scale[train_index],x_scale[test_index] 
  y_train,y_test = y[train_index],y[test_index]
  A = x_train.T.dot(x_train)
  B = np.linalg.inv(A)
  C = B.dot(x_train.T)   
  beta = C.dot(y_train)
  betas.append(beta)
  y_pred = x_test.dot(beta)
  r2.append(r2_score(y_test, y_pred))
  error = y_test-y_pred
  square_error = np.power(error,2)
  sum_square_error = np.sum(square_error)
  mse = sum_square_error/len(y_pred)
  errors.append(mse)

Train: [   0    1    2 ... 4997 4998 4999] Validation: [   3   10   11   12   13   16   21   22   30   34   39   40   42   52
   53   56   64   77   79   82  106  112  115  121  122  136  147  162
  163  167  176  181  183  187  200  202  204  205  207  210  218  225
  226  228  230  241  242  248  256  261  270  271  285  290  307  315
  323  324  327  329  331  334  349  353  354  355  357  358  362  366
  371  374  382  383  384  385  388  404  414  415  420  429  434  435
  444  454  455  462  464  466  469  473  479  484  485  487  491  506
  507  511  513  516  518  522  533  537  539  540  547  549  556  564
  569  571  589  597  609  617  619  627  631  633  637  645  647  656
  658  670  679  680  686  689  695  702  703  704  711  720  728  732
  736  738  741  742  746  755  757  758  759  764  785  787  789  806
  811  823  828  832  846  848  858  860  861  869  874  881  884  895
  916  918  919  922  925  926  930  931  933  940  943  947  957  959
  964  965  973  978  

In [17]:
r2

[0.9201327217966605,
 0.9140785320694662,
 0.914462346835153,
 0.9215864882505338,
 0.9186557048444113]

In [19]:
max_index = r2.index(max(r2))

In [20]:
betas[max_index]

array([1233511.89386493,  229735.65951694,  164142.63808291,
        121305.55498521,    2095.75818325,  150472.3591207 ])

In [21]:
best_beta=betas[max_index]

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scale, y, test_size = 0.3, random_state = 1)
y_pred = x_test.dot(best_beta)
print(y_pred)

[1554617.60388419 1582718.40389086  942700.36970904 ... 1101221.27216195
  975415.29048258 1729698.12604802]


In [25]:
r2_score(y_test, y_pred)

0.9167100151405999

**Q2**

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scale, y, test_size = 0.3, random_state = 1)
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.2, random_state = 1)

In [10]:
learning_rates = [0.001, 0.01, 0.1, 1]
iterations = 1000
n = len(x_train)
betas=[]

In [11]:
for learning in learning_rates:
  beta = np.zeros(6)
  for i in range(iterations):
    x0_gradient=0
    x1_gradient=0
    x2_gradient=0
    x3_gradient=0
    x4_gradient=0
    x5_gradient=0
    for j in range(n):
      a = x_train[j,0]
      b = x_train[j,1]
      c = x_train[j,2]
      d = x_train[j,3]
      e = x_train[j,4]
      f = y_train[j]
      x0_gradient+=(beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)
      x1_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*a)
      x2_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*b)
      x3_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*c)
      x4_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*d)
      x5_gradient+=((beta[0]+(beta[1]*a)+(beta[2]*b)+(beta[3]*c)+(beta[4]*d)+(beta[5]*e)-f)*e)
    beta[0]=beta[0]-learning/n*x0_gradient
    beta[1]=beta[1]-learning/n*x1_gradient
    beta[2]=beta[2]-learning/n*x2_gradient
    beta[3]=beta[3]-learning/n*x3_gradient
    beta[4]=beta[4]-learning/n*x4_gradient
    beta[5]=beta[5]-learning/n*x5_gradient
  betas.append(beta)

In [12]:
betas

[array([533864.38106375, 533864.38106375, 145139.83127764, 105826.36602249,
         65332.72820265,  20613.07320798]),
 array([616581.56074126, 616581.56074126, 227118.83257667, 162662.02019426,
        124606.48810405,    864.78988514]),
 array([6.16582360e+05, 6.16582360e+05, 2.27144336e+05, 1.62690885e+05,
        1.24964095e+05, 5.19710121e+02]),
 array([-18627725.27133379, -18627725.27133379,   -278292.14541702,
          -380595.3024752 ,   1540471.6374478 ,   1295552.33992304])]

In [14]:
r2 = []
from sklearn.metrics import r2_score
for beta in betas:
  y_pred_val = x_val.dot(beta)
  r2.append(r2_score(y_val, y_pred_val))

In [17]:
max_index = r2.index(max(r2))
optimal_beta = betas[max_index]
y_pred_final = x_test.dot(optimal_beta)
r2_final = r2_score(y_test, y_pred_final)

In [18]:
r2_final

-3.6892438685529987

**Q3**

In [4]:
columns = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration","num_doors", "body_style", "drive_wheels", "engine_location", "wheel_base", "length", "width", "height", "curb_weight", "engine_type", "num_cylinders", "engine_size", "fuel_system", "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm", "city_mpg", "highway_mpg", "price"]
df = pd.read_csv('/home/imports-85.csv',header=None, names = columns, na_values="?")

In [5]:
df = df.replace('?', np.nan)
df = df.dropna(subset=['price'])
df = df.fillna(df.mean())

In [6]:
df.isnull().sum()

symboling            0
normalized_losses    0
make                 0
fuel_type            0
aspiration           0
num_doors            2
body_style           0
drive_wheels         0
engine_location      0
wheel_base           0
length               0
width                0
height               0
curb_weight          0
engine_type          0
num_cylinders        0
engine_size          0
fuel_system          0
bore                 0
stroke               0
compression_ratio    0
horsepower           0
peak_rpm             0
city_mpg             0
highway_mpg          0
price                0
dtype: int64

In [7]:
#3.3.1
print(df['num_doors'].value_counts())

four    113
two      86
Name: num_doors, dtype: int64


In [8]:
print(df['num_cylinders'].value_counts())

four      157
six        24
five       10
eight       4
two         4
twelve      1
three       1
Name: num_cylinders, dtype: int64


In [9]:
cleanup_nums = {"num_doors":     {"four": 4, "two": 2},
                "num_cylinders": {"four": 4, "six": 6, "five": 5, "eight": 8,
                                  "two": 2, "twelve": 12, "three":3 }}
df = df.replace(cleanup_nums)

In [10]:
print(df['num_cylinders'].value_counts())

4     157
6      24
5      10
8       4
2       4
12      1
3       1
Name: num_cylinders, dtype: int64


In [11]:
#3.3.2
df = pd.get_dummies(df, columns = ["body_style", "drive_wheels"], prefix=["body", "drive"])

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 201 entries, 0 to 204
Data columns (total 32 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          201 non-null    int64  
 1   normalized_losses  201 non-null    float64
 2   make               201 non-null    object 
 3   fuel_type          201 non-null    object 
 4   aspiration         201 non-null    object 
 5   num_doors          199 non-null    float64
 6   engine_location    201 non-null    object 
 7   wheel_base         201 non-null    float64
 8   length             201 non-null    float64
 9   width              201 non-null    float64
 10  height             201 non-null    float64
 11  curb_weight        201 non-null    int64  
 12  engine_type        201 non-null    object 
 13  num_cylinders      201 non-null    int64  
 14  engine_size        201 non-null    int64  
 15  fuel_system        201 non-null    object 
 16  bore               201 non

In [13]:
#3.3.3
cols = ["make", "aspiration", "engine_location", "fuel_type"]
for col in cols:
  df[col] = df[col].astype('category')
  df[col] = df[col].cat.codes

In [14]:
df['make'].head()

0    0
1    0
2    0
3    1
4    1
Name: make, dtype: int8

In [15]:
#3.3.4
df["PFI_Code"] = np.where(df["fuel_system"].str.contains("pfi"), 1, 0)

In [16]:
del df["fuel_system"]

In [17]:
#3.3.5
df["OHC_Code"] = np.where(df["engine_type"].str.contains("ohc"), 1, 0)

In [18]:
del df["engine_type"]

In [25]:
#3.4
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x = df.loc[:, df.columns != 'price'].values
y = df.loc[:, df.columns == 'price'].values

x_train, x_test, y_train, y_test = train_test_split(x , y , test_size = 0.3, random_state = 1)
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [26]:
#3.5
df= df.dropna()
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
y_pred = reg.predict(x_test)
for i in range(y_test.shape[0]):
  y_test[i] = pd.to_numeric(y_test[i], errors='coerce')

In [27]:
#3.6
from sklearn.decomposition import PCA
pca=PCA(n_components=2)
x_new=pca.fit_transform(x)

In [29]:
x_train_new, x_test_new, y_train_new, y_test_new = train_test_split(x_new , y , test_size = 0.3, random_state = 1)

In [30]:
A=x_train_new.T.dot(x_train_new)
B=np.linalg.inv(A)
C=B.dot(x_train_new.T)
beta_new=C.dot(y_train_new)
print(beta_new)

[[10.7096861 ]
 [ 9.82790345]]
